version: "3"

volumes:
  caddy_data:
  caddy_config:

networks:
  logging:
    name: logging

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

services:
  website:
    container_name: website
    build: ./frontend
    restart: unless-stopped
    ports:
      - "8080:3000"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - logging
    logging: *default-logging

  caddy:
    container_name: caddy
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - logging
    logging: *default-logging

  loki:
    container_name: loki
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - logging

  promtail:
    container_name: promtail
    image: grafana/promtail:2.9.4
    volumes:
      - ./promtail.yml:/etc/promtail/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    networks:
      - logging
    logging: *default-logging

  grafana:
    container_name: grafana
    image: grafana/grafana:10.3.1
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana.yml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "3000:3000"
    networks:
      - logging
    logging: *default-logging
